name: 'Build and test'

on:
  pull_request:
  push:
    branches:
      - 'master'
  workflow_dispatch:

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=true -Dorg.gradle.parallel=true -Dorg.gradle.welcome=never

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: write
      pull-requests: write
      statuses: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Set up Java 17'
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          java-package: jdk+fx

      - name: 'Build'
        id: build
        uses: gradle/gradle-build-action@v3.3.2
        with:
          gradle-version: wrapper
          arguments: |
            build
            -x
            jar
            distTar
            distZip
            shadowDistTar
            shadowDistZip
            pmdMain
            pmdTest

      - name: 'Upload gradle reports'
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: gradle-reports
          path: 'build/reports/'
          retention-days: 1

      - name: 'Upload shadowJar'
        uses: actions/upload-artifact@v4
        with:
          name: spreadsheet.jar
          path: 'build/libs/spreadsheet-*.jar'
          retention-days: 90